export const SECTOR_DEFAULT_CATEGORIES: Record<string, { name: string; avgDurationMinutes: number }[]> = {
  DIAGNOSTIC: [
    { name: 'Blood Test (CBC / Complete Blood Count)', avgDurationMinutes: 15 },
    { name: 'Lipid Profile', avgDurationMinutes: 15 },
    { name: 'Liver Function Test (LFT)', avgDurationMinutes: 15 },
    { name: 'Kidney Function Test (KFT)', avgDurationMinutes: 15 },
    { name: 'Thyroid Profile (T3/T4/TSH)', avgDurationMinutes: 15 },
    { name: 'Diabetes / HbA1c / Fasting Sugar', avgDurationMinutes: 10 },
    { name: 'Urine Routine & Microscopy', avgDurationMinutes: 10 },
    { name: 'Stool Examination', avgDurationMinutes: 10 },
    { name: 'X-Ray (Chest / Spine / Limb)', avgDurationMinutes: 20 },
    { name: 'ECG / Electrocardiogram', avgDurationMinutes: 15 },
    { name: 'Ultrasound / Sonography (Abdomen)', avgDurationMinutes: 30 },
    { name: 'Ultrasound (Pelvis / Obstetric)', avgDurationMinutes: 30 },
    { name: 'Echocardiography (ECHO)', avgDurationMinutes: 40 },
    { name: 'CT Scan', avgDurationMinutes: 30 },
    { name: 'MRI Scan', avgDurationMinutes: 45 },
    { name: 'Mammography', avgDurationMinutes: 25 },
    { name: 'Bone Density (DEXA Scan)', avgDurationMinutes: 20 },
    { name: 'COVID-19 RT-PCR / Rapid Antigen', avgDurationMinutes: 15 },
    { name: 'Pap Smear / Cervical Cytology', avgDurationMinutes: 20 },
    { name: 'Full Body Health Checkup Package', avgDurationMinutes: 60 },
    { name: 'Vitamin D / B12 Test', avgDurationMinutes: 15 },
    { name: 'Culture & Sensitivity Test', avgDurationMinutes: 15 },
    { name: 'Report Collection', avgDurationMinutes: 5 },
  ],

  HOSPITAL: [
    { name: 'OPD — General Physician', avgDurationMinutes: 20 },
    { name: 'OPD — Cardiologist', avgDurationMinutes: 30 },
    { name: 'OPD — Orthopaedic', avgDurationMinutes: 25 },
    { name: 'OPD — Neurologist', avgDurationMinutes: 30 },
    { name: 'OPD — Gynaecologist', avgDurationMinutes: 25 },
    { name: 'OPD — Paediatrician', avgDurationMinutes: 20 },
    { name: 'OPD — Dermatologist', avgDurationMinutes: 20 },
    { name: 'OPD — ENT Specialist', avgDurationMinutes: 20 },
    { name: 'OPD — Ophthalmologist', avgDurationMinutes: 25 },
    { name: 'OPD — Diabetologist / Endocrinologist', avgDurationMinutes: 30 },
    { name: 'OPD — Psychiatrist / Counsellor', avgDurationMinutes: 45 },
    { name: 'OPD — Oncologist', avgDurationMinutes: 40 },
    { name: 'Dental Consultation & Treatment', avgDurationMinutes: 30 },
    { name: 'Emergency Triage', avgDurationMinutes: 10 },
    { name: 'Pharmacy / Medicine Collection', avgDurationMinutes: 10 },
    { name: 'Vaccination / Injection Room', avgDurationMinutes: 15 },
    { name: 'Dressing & Wound Care', avgDurationMinutes: 20 },
    { name: 'Physiotherapy Session', avgDurationMinutes: 45 },
    { name: 'Lab Sample Collection', avgDurationMinutes: 10 },
    { name: 'Report / Discharge Collection', avgDurationMinutes: 10 },
    { name: 'Insurance / TPA Desk', avgDurationMinutes: 25 },
    { name: 'Radiology / Imaging Registration', avgDurationMinutes: 15 },
  ],

  BANK: [
    { name: 'Cash Deposit', avgDurationMinutes: 10 },
    { name: 'Cash Withdrawal (Over the Counter)', avgDurationMinutes: 10 },
    { name: 'Cheque Submission / Clearance', avgDurationMinutes: 10 },
    { name: 'Demand Draft / Pay Order', avgDurationMinutes: 20 },
    { name: 'RTGS / NEFT / Fund Transfer', avgDurationMinutes: 15 },
    { name: 'Passbook Update', avgDurationMinutes: 5 },
    { name: 'Account Opening (Savings / Current)', avgDurationMinutes: 30 },
    { name: 'Fixed Deposit Opening / Closure', avgDurationMinutes: 20 },
    { name: 'Recurring Deposit', avgDurationMinutes: 15 },
    { name: 'Loan Inquiry (Home / Personal / Vehicle)', avgDurationMinutes: 45 },
    { name: 'Loan Application & Documentation', avgDurationMinutes: 60 },
    { name: 'Debit Card / Credit Card Issue or Replacement', avgDurationMinutes: 20 },
    { name: 'Net Banking & Mobile Banking Setup', avgDurationMinutes: 15 },
    { name: 'KYC / Aadhaar / PAN Update', avgDurationMinutes: 15 },
    { name: 'Locker Access', avgDurationMinutes: 15 },
    { name: 'Forex Exchange / Remittance', avgDurationMinutes: 20 },
    { name: 'Deceased Account / Nomination Update', avgDurationMinutes: 30 },
    { name: 'Grievance & General Customer Support', avgDurationMinutes: 20 },
    { name: 'Senior Citizen Services', avgDurationMinutes: 20 },
    { name: 'Gold Loan', avgDurationMinutes: 30 },
  ],

  RESTAURANT: [
    { name: 'Dine-In — Regular Table', avgDurationMinutes: 45 },
    { name: 'Dine-In — Family Section', avgDurationMinutes: 50 },
    { name: 'Dine-In — Couple / Romantic Seating', avgDurationMinutes: 60 },
    { name: 'Pre-Booked Table Check-In', avgDurationMinutes: 30 },
    { name: 'Buffet Entry (Lunch)', avgDurationMinutes: 60 },
    { name: 'Buffet Entry (Dinner)', avgDurationMinutes: 75 },
    { name: 'Takeaway / Parcel Order', avgDurationMinutes: 15 },
    { name: 'Home Delivery Order Pickup', avgDurationMinutes: 10 },
    { name: 'Quick Bites / Snacks Counter', avgDurationMinutes: 10 },
    { name: 'Breakfast Counter', avgDurationMinutes: 20 },
    { name: 'Bakery / Dessert Counter', avgDurationMinutes: 10 },
    { name: 'Bar / Beverage Counter', avgDurationMinutes: 15 },
    { name: 'Private Dining Room', avgDurationMinutes: 90 },
    { name: 'Rooftop / Outdoor Seating', avgDurationMinutes: 60 },
    { name: 'Birthday / Anniversary Table Setup', avgDurationMinutes: 30 },
    { name: 'Corporate Group Booking', avgDurationMinutes: 90 },
    { name: 'Jain / Dietary Special Counter', avgDurationMinutes: 20 },
    { name: 'Live Counter (Dosa / Chaat / Grill)', avgDurationMinutes: 15 },
  ],

  SALON: [
    { name: 'Haircut — Men (Regular)', avgDurationMinutes: 20 },
    { name: 'Haircut — Men (Designer / Fade)', avgDurationMinutes: 30 },
    { name: 'Beard Trim & Shaping', avgDurationMinutes: 15 },
    { name: 'Clean Shave', avgDurationMinutes: 15 },
    { name: 'Head Massage', avgDurationMinutes: 20 },
    { name: 'Haircut — Women (Short)', avgDurationMinutes: 40 },
    { name: 'Haircut — Women (Long / U-Cut / V-Cut)', avgDurationMinutes: 60 },
    { name: 'Hair Wash & Blow Dry', avgDurationMinutes: 30 },
    { name: 'Hair Colour — Global (Full Head)', avgDurationMinutes: 90 },
    { name: 'Hair Colour — Highlights / Balayage', avgDurationMinutes: 120 },
    { name: 'Hair Spa / Keratin Treatment', avgDurationMinutes: 60 },
    { name: 'Straightening / Smoothening', avgDurationMinutes: 90 },
    { name: 'Facial — Basic', avgDurationMinutes: 40 },
    { name: 'Facial — Gold / Diamond / Fruit', avgDurationMinutes: 60 },
    { name: 'Clean-Up (Express Facial)', avgDurationMinutes: 30 },
    { name: 'Bleach — Face / Arms', avgDurationMinutes: 20 },
    { name: 'D-Tan Pack', avgDurationMinutes: 25 },
    { name: 'Threading — Eyebrows / Upper Lip / Full Face', avgDurationMinutes: 10 },
    { name: 'Waxing — Full Arms or Full Legs', avgDurationMinutes: 30 },
    { name: 'Waxing — Full Body', avgDurationMinutes: 60 },
    { name: 'Manicure — Basic / Gel', avgDurationMinutes: 30 },
    { name: 'Pedicure — Basic / Spa', avgDurationMinutes: 40 },
    { name: 'Nail Art & Extensions', avgDurationMinutes: 60 },
    { name: 'Bridal / Party Makeup Package', avgDurationMinutes: 120 },
    { name: 'Pre-Bridal Package (Full Session)', avgDurationMinutes: 180 },
  ],

  VEHICLE_SERVICE: [
    { name: 'Engine Oil & Filter Change', avgDurationMinutes: 30 },
    { name: 'Air Filter Replacement', avgDurationMinutes: 15 },
    { name: 'Tyre Change / Rotation / Balancing', avgDurationMinutes: 30 },
    { name: 'Wheel Alignment', avgDurationMinutes: 30 },
    { name: 'Battery Check & Replacement', avgDurationMinutes: 20 },
    { name: 'General Periodic Service (Car)', avgDurationMinutes: 120 },
    { name: 'General Periodic Service (Two-Wheeler)', avgDurationMinutes: 60 },
    { name: 'Car Wash — Exterior', avgDurationMinutes: 20 },
    { name: 'Car Wash — Full Interior + Exterior Detailing', avgDurationMinutes: 60 },
    { name: 'AC Gas Refill & Performance Check', avgDurationMinutes: 60 },
    { name: 'AC Compressor / Condenser Service', avgDurationMinutes: 90 },
    { name: 'Brake Pad Replacement & Inspection', avgDurationMinutes: 40 },
    { name: 'Clutch & Gearbox Service', avgDurationMinutes: 90 },
    { name: 'Engine Diagnostics (OBD Scan)', avgDurationMinutes: 30 },
    { name: 'Suspension & Steering Check', avgDurationMinutes: 30 },
    { name: 'Denting & Painting (Minor)', avgDurationMinutes: 180 },
    { name: 'Windshield Chip Repair / Replacement', avgDurationMinutes: 60 },
    { name: 'Electrical & Wiring Repair', avgDurationMinutes: 60 },
    { name: 'PUC / Emission Certificate', avgDurationMinutes: 15 },
    { name: 'Insurance Claim & Accident Repair', avgDurationMinutes: 45 },
    { name: 'Headlight / Taillight Replacement', avgDurationMinutes: 20 },
    { name: 'Radiator Flush & Coolant Top-Up', avgDurationMinutes: 30 },
  ],
};
